---
users:
  count: 5
  startTime:
    max: 120
  runTime:
    min: 60
    max: 120

notebook:
  - source: print("Hello")
    assert_output: "Hello\n"
  - source: print("Goodbye")
    assert_output: "Goodbye\n"
