kind: ConfigMap
apiVersion: v1
metadata:
  name: benchmark
data:
  benchmark.yaml: |-
  {{ if .Values.benchmark }}{{- .Values.benchmark | nindent 4 }}{{ else }}{{ required "--set-file benchmark=./file is required" .Values.benchmark | quote }}{{ end }}
