apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: collector
  labels:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      app: hubtraf
      release: {{ .Release.Name }}
      component: collector
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        app: hubtraf
        release: {{ .Release.Name }}
        component: collector
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:0.12
        ports:
        - containerPort: 24224
        workingDir: /srv
        command:
          - /fluent-bit/bin/fluent-bit
          - -R
          - /fluent-bit/etc/parsers.conf
          - -i
          - forward
          - -o
          - file
          - -p
          - path=/srv/events.log
          - -p
          - match=*
          - -o
          - stdout
          - -p
          - match=*
          - -o
          - es
          - -p
          - Host=search-syzygy-spapk2l7ior7uu6ihjifvugele.ca-central-1.es.amazonaws.com
          - -p
          - Logstash_Format=On
          - -p
          - match=*
---
kind: Service
apiVersion: v1
metadata:
  name: collector
  labels:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
spec:
  selector:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
  ports:
  - protocol: TCP
    port: 24224
    targetPort: 24224
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: collector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      app: hubtraf
      release: {{ .Release.Name }}
      component: collector
