apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: collector
  labels:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      app: hubtraf
      release: {{ .Release.Name }}
      component: collector
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        app: hubtraf
        release: {{ .Release.Name }}
        component: collector
    spec:
      volumes:
        - name: fluent-parsers-conf
          configMap:
            name: fluent-parsers-conf
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.3.9-debug
        ports:
        - containerPort: 24224
        workingDir: /srv
        volumeMounts:
          - name: fluent-parsers-conf
            mountPath: /mnt
        command:
          - /fluent-bit/bin/fluent-bit
          - -R
          - /fluent-bit/etc/parsers.conf
          - -i
          - forward
          - -F
          - parser
          - -p
          - Match=*
          - -p
          - Key_Name=log
          - -p
          - Parser=docker
          - -o
          - es
          - -p
          - Host=search-syzygy-spapk2l7ior7uu6ihjifvugele.ca-central-1.es.amazonaws.com
          - -p
          - Port=443
          - -p
          - Logstash_Format=On
          - -p
          - Match=*
          - -p
          - TLS=On
          - Retry_Limit=False
          - -o
          - stdout
          - -p
          - Match=*
          - -o
          - file
          - -p
          - Match=*
---
kind: Service
apiVersion: v1
metadata:
  name: collector
  labels:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
spec:
  selector:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
  ports:
  - protocol: TCP
    port: 24224
    targetPort: 24224
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: collector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      app: hubtraf
      release: {{ .Release.Name }}
      component: collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-parsers-conf
data:
  parsers-new.conf: |
    [PARSER]
      Name   docker
      Format json
      Time_Key time
      Time_Format %d/%b/%Y:%H:%M:%S.%L
