apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: collector
  labels:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      app: hubtraf
      release: {{ .Release.Name }}
      component: collector
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        app: hubtraf
        release: {{ .Release.Name }}
        component: collector
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.3.9
        ports:
        - containerPort: 24224
        workingDir: /srv
        command:
          - /fluent-bit/bin/fluent-bit
          - -R
          - /fluent-bit/etc/parsers.conf
          - -i
          - forward
          - -F
          - parser
          - -p
          - Match=*
          - -p
          - Key_Name=log
          - -p
          - Parser=docker
          {{- if .Values.es.endpoint }}
          - -o
          - es
          - -p
          - Host={{- .Values.es.endpoint }}
          - -p
          - Port=443
          - -p
          - Logstash_Format=On
          - -p
          - Match=*
          - -p
          - TLS=On
          - -p
          - Retry_Limit=False
          {{- end }}
          - -o
          - stdout
          - -p
          - Match=*
          - -o
          - file
          - -p
          - Match=*
---
kind: Service
apiVersion: v1
metadata:
  name: collector
  labels:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
spec:
  selector:
    heritage: {{ .Release.Service }}
    app: hubtraf
    release: {{ .Release.Name }}
    component: collector
  ports:
  - protocol: TCP
    port: 24224
    targetPort: 24224
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: collector
spec:
  minAvailable: 1
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      app: hubtraf
      release: {{ .Release.Name }}
      component: collector
